site_name: Anansi's web of tutorials
site_url: https://0xanansi.github.io/wiki/
site_dir: public
docs_dir: docs
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep orange
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.top
# Extensions
markdown_extensions:
    - footnotes
    - attr_list
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.magiclink
    - pymdownx.tasklist
    - pymdownx.emoji
    - admonition
    - toc.integrate
permalink: true
plugins:
    - search
    - roamlinks

