site_name: Anansi's web of tutorials
site_url: https://0xanansi.github.io/wiki/
site_dir: public
docs_dir: docs
nav:
    - Home: index.md
    - About: about.md
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep orange
# Extensions
markdown_extensions:
    - footnotes
    - attr_list
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.magiclink
    - pymdownx.tasklist
    - pymdownx.emoji
    - admonition
    - toc:
    permalink: true
plugins:
    - search
    - roamlinks

